/**
 * MurdleControlPlane
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CurrentPlayerRoundState } from './CurrentPlayerRoundState';
import { PlayerScore } from './PlayerScore';
import { Round } from './Round';
import { HttpFile } from '../http/http';

export class GameStructure {
    'gameId': string;
    'playerScores': Array<PlayerScore>;
    'currentPlayerRoundStates': Array<CurrentPlayerRoundState>;
    'rounds': Array<Round>;
    'lobbyId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "gameId",
            "baseName": "gameId",
            "type": "string",
            "format": ""
        },
        {
            "name": "playerScores",
            "baseName": "playerScores",
            "type": "Array<PlayerScore>",
            "format": ""
        },
        {
            "name": "currentPlayerRoundStates",
            "baseName": "currentPlayerRoundStates",
            "type": "Array<CurrentPlayerRoundState>",
            "format": ""
        },
        {
            "name": "rounds",
            "baseName": "rounds",
            "type": "Array<Round>",
            "format": ""
        },
        {
            "name": "lobbyId",
            "baseName": "lobbyId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameStructure.attributeTypeMap;
    }
    
    public constructor() {
    }
}

