/**
 * MurdleControlPlane
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LetterStatus } from './LetterStatus';
import { HttpFile } from '../http/http';

export class GuessedLetterResult {
    'letter': string;
    'status': LetterStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "letter",
            "baseName": "letter",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "LetterStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GuessedLetterResult.attributeTypeMap;
    }
    
    public constructor() {
    }
}

