/**
 * MurdleControlPlane
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PublicUser } from './PublicUser';
import { HttpFile } from '../http/http';

export class PlayerScore {
    'score': number;
    'totalTime': number;
    'player': PublicUser;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "score",
            "baseName": "score",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "totalTime",
            "baseName": "totalTime",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "player",
            "baseName": "player",
            "type": "PublicUser",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlayerScore.attributeTypeMap;
    }
    
    public constructor() {
    }
}

