/**
 * MurdleControlPlane
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GuessedLetterResult } from './GuessedLetterResult';
import { HttpFile } from '../http/http';

export class PlayerGuess {
    'guessLetterResult': Array<GuessedLetterResult>;
    'guessedWord': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "guessLetterResult",
            "baseName": "guessLetterResult",
            "type": "Array<GuessedLetterResult>",
            "format": ""
        },
        {
            "name": "guessedWord",
            "baseName": "guessedWord",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlayerGuess.attributeTypeMap;
    }
    
    public constructor() {
    }
}

