/**
 * MurdleControlPlane
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RoundStatus } from './RoundStatus';
import { HttpFile } from '../http/http';

export class Round {
    'wordleWord'?: string;
    'startTime': number;
    'endTime': number;
    'status': RoundStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "wordleWord",
            "baseName": "wordleWord",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "number",
            "format": ""
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "RoundStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Round.attributeTypeMap;
    }
    
    public constructor() {
    }
}

